<!-- ADDING TO CART -->
<div class="ajaxcartpreview_hide ajaxcartpreview_pos" id="fe_ajaxcartpreview_addingtocart">
	<p class="title">Adding to Cart</p>
    <p class="sub_title">Please wait while we update your cart...</p>
    <p class="loader"><img src="../../../../../../../../../skin/frontend/default/default/images/fisheye/ajaxcartpreview/loader.gif" /></p>
</div>

<!-- FAILED TO ADD TO CART -->
<div class="ajaxcartpreview_hide ajaxcartpreview_pos" id="fe_ajaxcartpreview_failedcart">
	<p class="title">Failed to Add to Cart</p>
    <p id="fe_ajaxcartpreview_failedcart_close"></p>
	<p id="fe_ajaxcartpreview_failedcart_msg"></p>
</div>

<!-- SUCCESSFULLY ADDED TO CART -->
<div class="ajaxcartpreview_hide ajaxcartpreview_pos" id="fe_ajaxcartpreview_successcart">
	<p class="title">Successfully Added to Cart</p>
	<p id="fe_ajaxcartpreview_successcart_msg"></p>
    
    <span id="fe_addtocart_success_closebutton"><a title="Continue Shopping" class="button left">Continue Shopping</a></span>
    <a href="/checkout" title="Continue to Checkout" class="button right">Continue to Checkout</a>
</div>