<!--AjaxCartPreview System Variables -->
<script type="text/javascript">
	FE_BASE_URL = '<?php echo Mage::getBaseUrl(); ?>';
	FE_AJAXCART_ENABLED = <?php echo Mage::getStoreConfig('ajaxcartpreview/ajaxcart/ajaxcart_enabled'); ?>;
	FE_CARTPREVIEW_ENABLED = <?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_enabled'); ?>;
	FE_CARTPREVIEW_SHOWMSG = <?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_showmsg'); ?>;
	FE_CARTPREVIEW_TARGET = '<?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_target'); ?>';
	
	FE_CARTPREVIEW_SHOWEFFECT = '<?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_showeffect'); ?>';
	FE_CARTPREVIEW_HIDEEFFECT = '<?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_hideeffect'); ?>';
	FE_CARTPREVIEW_SHOWEFFECT_FADETIME = <?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_showeffect_fadetime'); ?>;
	FE_CARTPREVIEW_HIDEEFFECT_FADETIME = <?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_hideeffect_fadetime'); ?>;
	FE_CARTPREVIEW_SHOWEFFECT_SLIDEPOS = '<?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_showeffect_slidepos'); ?>';
	FE_CARTPREVIEW_HIDEEFFECT_SLIDEPOS = '<?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_hideeffect_slidepos'); ?>';
	FE_CARTPREVIEW_SHOWEFFECT_SLIDETIME = <?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_showeffect_slidetime'); ?>;
	FE_CARTPREVIEW_HIDEEFFECT_SLIDETIME = <?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_hideeffect_slidetime'); ?>;
	
	FE_CARTPREVIEW_HIDEEFFECT_DELAY = <?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_hideeffect_delay'); ?>;
	
	FE_AJAXCART_TIMETOHIDECP = <?php echo Mage::getStoreConfig('ajaxcartpreview/ajaxcart/ajaxcart_hidecpreview'); ?>;
	FE_CARTPREVIEW_INIT = <?php echo Mage::getStoreConfig('ajaxcartpreview/cartpreview/cartpreview_preloadcart'); ?>;
</script>