<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Searchautocomplete
 * @version    3.2.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php

?>

    <ul>
        <li class="aw_hidden" id="aw_hidden"></li>
            <?php foreach ($this->getItems() as $item): ?>
                <?php if ((int) Mage::getStoreConfig('searchautocomplete/interface/open_in_new_window')): ?>
                        <li onClick="window.open('<?php echo $item['url'] ?>', '_blank')">
                            <input type="hidden" name="url" value="setLocation('<?php echo $item['url'] ?>')">
                 <?php else: ?>
                        <li onClick="setLocation('<?php echo $item['url'] ?>')">
                            <input type="hidden" name="url" value="setLocation('<?php echo $item['url'] ?>')">
                 <?php endif; ?>
                 <?php echo $item['content'] ?>
                        </li>
            <?php endforeach; ?>
    </ul>
