<div id="block_notice_ebay_configuration_category_edit_primary" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('eBay Primary Category'); ?>">
    <?php echo Mage::helper('M2ePro')->__('On the Specifics tab there are all variety of used Specifics sets for the current category.
    <br>Created date is the date when they were saved. If you replace the category to another one, you will need to specify Specifics settings for all created dates.'); ?>
</div>