<!-- CARTPREVIEW LOADING -->
<div class="ajaxcartpreview_hide" id="fe_ajaxcartpreview_cartpreviewloading">
    <div class="cartpreviewloading">
    	<p class="title">Updating one moment please...</p>
    	<p class="loader"><img src="../../../../../../../../../skin/frontend/default/default/images/fisheye/ajaxcartpreview/loader.gif" /></p>
	</div>
</div>

<!-- CARTPREVIEW LOADING -->
<div class="ajaxcartpreview_hide" id="fe_ajaxcartpreview_content"></div>